name: filt_app
description: App Filt Cgil
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.2
  http: ^1.1.0
  syncfusion_flutter_pdfviewer: 22.1.34 # Versione fissa piÃ¹ compatibile
  url_launcher: ^6.1.11

flutter:
  uses-material-design: true
  
