name: filt_app
description: App FILT Settore Trasporti - Protetto
version: 1.3.2
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.1
  http: ^0.13.5
  syncfusion_flutter_pdfviewer: ^20.4.38
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
